version: '3'

vars:
  XC_PROJ: Cider.xcodeproj
  XC_ARCHIVE: dest/Cider.xcarchive
  CIDER_DEST_APP: dest/Cider.app
  DEBUG_BUILD_DIR:
    sh: $(command -v bkt >/dev/null 2>&1 && echo "bkt --cwd --") xcodebuild clean -project {{.XC_PROJ}} -scheme Cider -sdk macosx -configuration Debug -showBuildSettings | $(command -v rg >/dev/null 2>&1 && echo "rg" || echo "grep") -m 1 TARGET_BUILD_DIR | grep -oEi "\/.*"
  RELEASE_BUILD_DIR:
    sh: $(command -v bkt >/dev/null 2>&1 && echo "bkt --cwd --") xcodebuild clean -project {{.XC_PROJ}} -scheme "Cider - Release" -sdk macosx -configuration Release -quiet -showBuildSettings | $(command -v rg >/dev/null 2>&1 && echo "rg" || echo "grep") -m 1 TARGET_BUILD_DIR | grep -oEi "\/.*"

tasks:
  default:
    desc: "Build, Run, Perform Tasks with Taskfile"
    silent: true
    cmds:
      - echo -e "Build, Run, Perform Tasks with Taskfile!\nRun 'task build-xc' to build Cider, consult README.md for documentation"

  quickstart:
    desc: "Quickstart command for setting everything up as a Cider developer"
    cmds:
      - brew bundle
      - task: install-deps:all-js
      - task: build:discord-rpc-lib
      - task: build:native-utils-lib
      - task: build:all-js
      - task: fetch:google-services

  build:discord-rpc-lib:
    desc: "Build DiscordRPCAgent"
    dir: DiscordRPCAgent/
    sources:
      - src/**/*.rs
    generates:
      - target/universal/libdiscord_rpc_agent.a
    cmds:
      - sh build.sh

  clean:discord-rpc-lib:
    desc: "Clean DiscordRPCAgent's target folder"
    prompt: "Cleaning DiscordRPCAgent's target folder, do you want to continue?"
    dir: DiscordRPCAgent/
    cmds:
      - rm -rf target/

  build:cxx-native-utils-lib:
    desc: "Build CXX NativeUtils"
    dir: NativeUtils/
    sources:
      - cxx/**/*.cpp
      - cxx/**/*.h
      - CMakeLists.txt
    generates:
      - build/libCider_CXXNativeUtils.a
    cmds:
      - mkdir -p build/
      - (cd build/;cmake .. -G Ninja)
      - cmake --build build/ --target Cider_CXXNativeUtils -j 8

  build:rs-native-utils-lib:
    desc: "Build Rust NativeUtils"
    dir: NativeUtils/
    sources:
      - src/**/*.rs
      - Cargo.toml
      - build.rs
    generates:
      - target/universal/libnative_utils.a
    cmds:
      - sh build.sh

  build:native-utils-lib:
    desc: "Build NativeUtils"
    cmds:
      - task: build:rs-native-utils-lib
      - task: build:cxx-native-utils-lib

  clean:native-utils-lib:
    desc: "Clean NativeUtils's target folder"
    prompt: "Cleaning NativeUtils' target folder, do you want to continue?"
    dir: NativeUtils/
    cmds:
      - rm -rf target/
      - rm -rf build/

  install-deps:cpa-js:
    dir: 'CiderPlaybackAgent/Web Scripts/'
    desc: "Install CiderPlaybackAgent's dependencies with Yarn"
    cmds:
      - yarn

  install-deps:cwa-js:
    dir: 'CiderWebAuth/'
    desc: "Install CiderWebAuth's dependencies with Yarn"
    cmds:
      - yarn

  install-deps:dev-utils-js:
    dir: 'CiderDevUtils/'
    desc: "Install CiderDevUtils' dependencies with Yarn"
    cmds:
      - yarn

  install-deps:all-js:
    desc: "Install all JS dependencies"
    cmds:
      - task: install-deps:cwa-js
      - task: install-deps:cpa-js
      - task: install-deps:dev-utils-js

  build:cwa-js:
    dir: 'CiderWebAuth/'
    desc: "Build CiderWebAuth"
    sources:
      - src/**/*.ts
    generates:
      - dist/ciderwebauth.js
    cmds:
      - yarn build

  build:cpa-js:
    dir: 'CiderPlaybackAgent/Web Scripts/'
    desc: "Build CiderPlaybackAgent's Scripts"
    sources:
      - src/**/*.ts
    generates:
      - dist/ciderplaybackagent.js
    cmds:
      - yarn build

  build:all-js:
    cmds:
      - task: build:cwa-js
      - task: build:cpa-js

  build:xc:
    desc: "Build all targets including Cider and CiderPlaybackAgent"
    preconditions:
      - test -f "`which xcbeautify`"
    cmds:
      - xcodebuild -project {{.XC_PROJ}} -configuration Debug -sdk macosx -destination platform=macOS,arch=`arch` -scheme Cider build | xcbeautify

  run:xc:
    desc: "Run Cider Debug"
    cmds:
      - open {{.DEBUG_BUILD_DIR}}/*.app

  run:xc-release:
    desc: "Run Cider Release"
    cmds:
      - open {{.RELEASE_BUILD_DIR}}/*.app

  open:xc-proj:
    desc: "Open Cider.xcodeproj"
    cmds:
      - open {{.XC_PROJ}}

  open:debug-build-dir:
    desc: "Open Debug build folder in Finder"
    cmds:
      - open {{.DEBUG_BUILD_DIR}}

  open:release-build-dir:
    desc: "Open Release build folder in Finder"
    cmds:
      - open {{.RELEASE_BUILD_DIR}}

  clean:xc:
    desc: "Clean Xcode build folder"
    prompt: "Cleaning Xcode build folder, do you want to continue?"
    preconditions:
      - test -f "`which xcbeautify`"
    cmds:
      - xcodebuild -project {{.XC_PROJ}} clean | xcbeautify

  archive:xc:
    desc: "Archive Cider Release"
    generates:
      - "{{.XC_ARCHIVE}}"
    preconditions:
      - test -f "`which xcbeautify`"
    cmds:
      - rm -rf {{.XC_ARCHIVE}}
      - xcodebuild -project {{.XC_PROJ}} -scheme "Cider - Release" archive -configuration Release -sdk macosx -destination platform=macOS,name="Any Mac" -archivePath {{.XC_ARCHIVE}} | xcbeautify

  archive:build-app-bundle:
    desc: "Export .app bundle from .xcarchive"
    sources:
      - "{{.XC_ARCHIVE}}"
    generates:
      - "{{.CIDER_DEST_APP}}"
    preconditions:
      - test -f "`which xcbeautify`"
    cmds:
      - rm -rf {{.CIDER_DEST_APP}}
      - (cd dest/; rm -f DistributionSummary.plist ExportOptions.plist Packaging.log)
      - xcodebuild -exportArchive -archivePath {{.XC_ARCHIVE}} -exportPath dest/ -exportOptionsPlist ExportOptions.plist | xcbeautify

  build:dmg:
    desc: "Build DMG for input .app"
    cmds:
      - mkdir -p dest/
      - create-dmg --volname "Cider for macOS" --window-size 600 dest/Cider.dmg {{.CLI_ARGS}}

  start:dev-server:
    dir: 'CiderDevUtils/'
    desc: "Start Dev Server for compiling JS in Xcode build scripts"
    cmds:
      - yarn start

  generate:js-licences:
    desc: "Generate licences from JavaScript dependencies"
    cmds:
      - task: generate:cpa-licences
      - task: generate:cwa-licences

  fetch:google-services:
    desc: "Fetch GoogleServices-Info.plist"
    dir: "CiderDevUtils/"
    env:
      CWD: "../"
    cmds:
      - yarn run fns/fetch-google-service

  verify:toolchain:
    desc: "Verify build toolchain"
    dir: "CiderDevUtils/"
    cmds:
      - yarn run fns/verify-and-install-toolchain

  scan:unused-code:
    desc: "Scan for unused code"
    cmds:
      - periphery scan

  sim:enable-stage-manager:
    desc: "Enable Stage Manager for running iPad simulator"
    cmds:
      - xcrun simctl spawn booted defaults write -g SBChamoisWindowingEnabled -bool YES

  sim:disable-stage-manager:
    desc: "Disable Stage Manager for running iPad simulator"
    cmds:
      - xcrun simctl spawn booted defaults write -g SBChamoisWindowingEnabled -bool NO

  kill:cider-playback-agent:
    aliases: [ kill-cpa ]
    desc: "Kill a hanging CiderPlaybackAgent process"
    cmds:
      - killall "CiderPlaybackAgent"
