version: '3'

tasks:
  default:
    desc: "Build, Run, Perform Tasks with Taskfile"
    silent: true
    cmds:
      - echo -e "Build, Run, Perform Tasks with Taskfile!\nRun 'task build-xc' to build Cider, consult README.md for documentation"

  build:discord-rpc-lib:
    desc: "Build DiscordRPCAgent"
    dir: DiscordRPCAgent/
    sources:
      - src/**/*.rs
    generates:
      - target/universal/libdiscord_rpc_agent.a
    cmds:
      - sh build.sh

  clean:discord-rpc-lib:
    desc: "Clean DiscordRPCAgent's target folder"
    dir: DiscordRPCAgent/
    cmds:
      - rm -rf target/

  build:cxx-native-utils-lib:
    desc: "Build CXX NativeUtils"
    dir: NativeUtils/
    sources:
      - cxx/**/*.cpp
      - cxx/**/*.h
      - CMakeLists.txt
    generates:
      - build/libCider_CXXNativeUtils.a
    cmds:
      - mkdir -p build/
      - (cd build/;cmake .. -G Ninja)
      - cmake --build build/ --target Cider_CXXNativeUtils -j 8

  build:rs-native-utils-lib:
    desc: "Build Rust NativeUtils"
    dir: NativeUtils/
    sources:
      - src/**/*.rs
      - Cargo.toml
      - build.rs
    generates:
      - target/universal/libnative_utils.a
    cmds:
      - sh build.sh

  build:native-utils-lib:
    desc: "Build NativeUtils"
    cmds:
      - task: build:rs-native-utils-lib
      - task: build:cxx-native-utils-lib

  clean:native-utils-lib:
    desc: "Clean NativeUtils's target folder"
    dir: NativeUtils/
    cmds:
      - rm -rf target/
      - rm -rf build/

  install-deps:cpa-js:
    dir: 'CiderPlaybackAgent/Web Scripts/'
    desc: "Install CiderPlaybackAgent's dependencies with Yarn"
    cmds:
      - yarn

  install-deps:cwa-js:
    dir: 'CiderWebAuth/'
    desc: "Install CiderWebAuth's dependencies with Yarn"
    cmds:
      - yarn

  install-deps:dev-utils-js:
    dir: 'CiderDevUtils/'
    desc: "Install CiderDevUtils' dependencies with Yarn"
    cmds:
      - yarn

  install-deps:all-js:
    desc: "Install all JS dependencies"
    cmds:
      - task: install-deps:cwa-js
      - task: install-deps:cpa-js
      - task: install-deps:dev-utils-js

  build:cwa-js:
    dir: 'CiderWebAuth/'
    desc: "Build CiderWebAuth"
    sources:
      - src/**/*.ts
    generates:
      - dist/ciderwebauth.js
    cmds:
      - yarn build

  build:cpa-js:
    dir: 'CiderPlaybackAgent/Web Scripts/'
    desc: "Build CiderPlaybackAgent's Scripts"
    sources:
      - src/**/*.ts
    generates:
      - dist/ciderplaybackagent.js
    cmds:
      - yarn build

  build:all-js:
    cmds:
      - task: build:cwa-js
      - task: build:cpa-js

  build:xc:
    desc: "Build all targets including Cider and CiderPlaybackAgent"
    cmds:
      - xcodebuild -workspace Cider.xcworkspace -configuration Debug -sdk macosx -destination platform=macOS,arch=`arch` -scheme Cider build

  run:xc:
    desc: "Run Cider"
    cmds:
      - open $(xcodebuild -workspace Cider.xcworkspace -scheme Cider -sdk macosx -configuration Debug -destination platform=macOS,arch=`arch` -quiet -showBuildSettings | grep -m 1 TARGET_BUILD_DIR | grep -oEi "\/.*")/*.app

  clean:xc:
    desc: "Clean Xcode build folder"
    cmds:
      - xcodebuild -workspace Cider.xcworkspace clean

  build:dmg:
    desc: "Build DMG for Cider (Dev).app"
    vars:
      CIDER_DMG: "dist/Cider.dmg"
      DEBUG_CIDER_APP:
        sh: xcodebuild -workspace Cider.xcworkspace -scheme Cider -sdk macosx -configuration Debug -destination platform=macOS,arch=`arch` -quiet -showBuildSettings | grep -m 1 TARGET_BUILD_DIR | grep -oEi "\/.*"
    cmds:
      - open "{{.DEBUG_CIDER_APP}}"/*.app

  start:dev-server:
    dir: 'CiderDevUtils/'
    desc: "Start Dev Server for compiling JS in Xcode build scripts"
    cmds:
      - yarn start

  generate:js-licences:
    desc: "Generate licences from JavaScript dependencies"
    cmds:
      - task: generate:cpa-licences
      - task: generate:cwa-licences

  fetch:google-services:
    desc: "Fetch GoogleServices-Info.plist"
    dir: "CiderDevUtils/"
    env:
      CWD: "../"
    cmds:
      - yarn run fns/fetch-google-service

  verify:toolchain:
    desc: "Verify build toolchain"
    dir: "CiderDevUtils/"
    cmds:
      - yarn run fns/verify-and-install-toolchain

  scan:unused-code:
    desc: "Scan for unused code"
    cmds:
      - periphery scan

  kill:cider-playback-agent:
    aliases: [ kill-cpa ]
    desc: "Kill a hanging CiderPlaybackAgent process"
    cmds:
      - killall "CiderPlaybackAgent"
