version: '3'

tasks:
  default:
    desc: "Build, Run, Perform Tasks with Taskfile"
    silent: true
    cmds:
      - echo -e "Build, Run, Perform Tasks with Taskfile!\nRun 'task build-xc' to build Cider, consult README.md for documentation"

  build-discord-rpc-lib:
    desc: "Build DiscordRPCAgent"
    dir: DiscordRPCAgent/
    sources:
      - src/**/*.rs
    generates:
      - target/universal/libdiscord_rpc_agent.a
    cmds:
      - sh build.sh

  clean-discord-rpc-lib:
    desc: "Clean DiscordRPCAgent's target folder"
    dir: DiscordRPCAgent/
    cmds:
      - rm -rf target/

  build-native-utils-lib:
    desc: "Build NativeUtils"
    dir: NativeUtils/
    sources:
      - src/**/*.rs
    generates:
      - target/universal/libnative_utils.a
    cmds:
      - sh build.sh

  clean-native-utils-lib:
    desc: "Clean NativeUtils's target folder"
    dir: NativeUtils/
    cmds:
      - rm -rf target/

  install-cpa-js-deps:
    dir: 'CiderPlaybackAgent/Web Scripts/'
    desc: "Install CiderPlaybackAgent's dependencies with Yarn"
    cmds:
      - yarn

  install-cwa-js-deps:
    dir: 'CiderWebAuth/'
    desc: "Install CiderWebAuth's dependencies with Yarn"
    cmds:
      - yarn

  install-dev-server-js-deps:
    dir: 'CiderDevServer/'
    desc: "Install CiderDevServer's dependencies with Yarn"
    cmds:
      - yarn

  install-js-deps:
    desc: "Install all JS dependencies"
    cmds:
      - task: install-cpa-js-deps
      - task: install-cwa-js-deps
      - task: install-dev-server-js-deps

  build-cwa-js:
    dir: 'CiderWebAuth/'
    desc: "Build CiderWebAuth"
    sources:
      - src/**/*.ts
    generates:
      - dist/index.js
    cmds:
      - yarn build

  build-cpa-js:
    dir: 'CiderPlaybackAgent/Web Scripts/'
    desc: "Build CiderPlaybackAgent's Scripts"
    sources:
      - src/**/*.ts
    generates:
      - dist/index-cpa.js
    cmds:
      - yarn build

  build-all-js:
    cmds:
      - task: build-cwa-js
      - task: build-cpa-js

  install-pod-plugins:
    desc: "Install all CocoaPods plugin dependencies"
    preconditions:
      - test -x $(which bundle)
    cmds:
      - bundle install

  build-xc:
    desc: "Build all targets including Cider and CiderPlaybackAgent"
    cmds:
      - xcodebuild -workspace Cider.xcworkspace -configuration Debug -sdk macosx -destination platform=macOS,arch=`arch` -scheme Cider build

  run-xc:
    desc: "Run Cider"
    cmds:
      - open $(xcodebuild -workspace Cider.xcworkspace -scheme Cider -sdk macosx -configuration Debug -destination platform=macOS,arch=`arch` -quiet -showBuildSettings | grep -m 1 TARGET_BUILD_DIR | grep -oEi "\/.*")/Cider.app

  clean-xc:
    desc: "Clean Xcode build folder"
    cmds:
      - xcodebuild -workspace Cider.xcworkspace clean

  start-dev-server:
    dir: 'CiderDevServer/'
    desc: "Start Dev Server for compiling JS in Xcode build scripts"
    cmds:
      - yarn start

  kill-cider-playback-agent:
    aliases: [kill-cpa]
    desc: "Kill a hanging CiderPlaybackAgent process"
    cmds:
      - killall "CiderPlaybackAgent"
